---
- "[ ╯ '□']╯︵┻━┻)"
- "[ ╯ °□°]╯︵┻━┻)"
- "[ ╯ಠ益ಠ]╯彡┻━┻)"
- "[ ╯ ≧∇≦]╯︵┸━┸)"
- "[ ╯´･ω･]╯︵┸━┸)"
- "[ ╯ ರ ~ರ]╯︵┻━┻)"
- "[ ╯ ✧Д✧]╯︵┻━┻)"
- "[ ╯ TДT]╯︵┻━┻)"
- "[ ╯ `^´]╯︵┻━┻)"
- "[ ╯ '▽ ']╯︵┻━┻)"
- "[ ╯ ｀□´]╯︵┻━┻)"
- "[ ╯｀皿´]╯︵┻━┻)"
- "[ ╯ ՞▃՞]╯︵┻━┻)"
- "[ ╯ -▃-]╯︵┻━┻)"
- "[ ╯ '▃']╯︵┻━┻)"
- "[ ╯ ﾟOﾟ]╯︵┻━┻)"
- "[ ╯ ￣^￣]╯︵┻━┻)"
- "[ ╯ -_-]╯︵┻━┻)"
- "[ ╯ '~']╯︵┻━┻)"
- "[ ╯ >_<]╯︵┻━┻)"
- "[ ╯ ಥ ⌒ಥ]╯︵┻━┻)"
- "[ ╯ ﾟ⊿ﾟ]╯︵┻━┻)"
- "[ ╯ `-`]╯︵┻━┻)"
- "[ ╯ ￣□￣]╯︵┻━┻)"
- "[ ╯ ﾟ▽ﾟ]╯︵┻━┻)"
- "[ ╯ ゜-゜]╯︵┻━┻)"
- "[ ╯ ຈل͜ຈ]╯︵┻━┻)"
- "[ ╯ ･_･]╯︵┻━┻)"
- "[ ╯ ツ]╯︵┻━┻)"
